$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native-permissions/scripts/setup.rb'

require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
     "react-native/scripts/react_native_pods.rb",
     {paths: [process.argv[1]]},
   )', __dir__]
).strip

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

prepare_react_native_project!

target 'somacy' do

  # ✅ ADD THIS BLOCK (VERY IMPORTANT)
  setup_permissions([
    'Camera',
    'PhotoLibrary',
    'PhotoLibraryAddOnly',
    'LocationWhenInUse',
  ])

  config = use_native_modules!

  use_frameworks! :linkage => :static
  pod 'GoogleMaps'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end
